version: '3.8'

services:
  hexserver2:
    build: ./hexServer2
    container_name: hexserver2_service
    network_mode: "host"
    ports:
      - "50052:50052"

  sup1:
    build: ./Sup1
    container_name: sup1_service
    network_mode: "host"
    stdin_open: true
    tty: true
    depends_on:
      - hexserver2
