version: '3.8'

services:
  hexserver3:
    build: ./hexServer3
    container_name: hexserver3_service
    network_mode: "host"
    ports:
      - "50053:50053"

  sup2:
    build: ./Sup2
    container_name: sup2_service
    network_mode: "host"
    stdin_open: true
    tty: true
    depends_on:
      - hexserver3
